---
- name: Clone dotfiles
  git:
    repo: git@bitbucket.org:andybold/dotfiles.git
    dest: /Users/andrewbold/src/me/dotfiles
    update: yes
    clone: yes

- name: Remove all crap from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: "{{ dockitems_to_remove  }}"

- name: Check if items in dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: "{{ dockitems_to_persist }}"

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: "{{ dockitems_to_persist }}"

- name: Install hexo
  shell: npm install -g '{{ item }}'
  with_items: "{{ npm_packages }}"

- name: Configure file associations
  shell: "{{ item }}"
  with_items:
    - "duti -s org.gnu.Emacs org editor"
    - "duti -s org.gnu.Emacs opml editor"
    - "duti -s org.gnu.Emacs md editor"

- name: Setting macOS defaults
  debug:
    msg: ""

- name: Expand save panel by default
  shell: "defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true"

- name: Expand print panel by default
  shell: "defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true"

- name: Restart automatically if the computer freezes
  shell: "systemsetup -setrestartfreeze on"

- name: Disable auto-correct
  shell: "defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false"

- name: Save screenshots in PNG format (other options are BMP, GIF, JPG, PDF, TIFF)
  shell: "defaults write com.apple.screencapture type -string 'png'"

- name: Display full POSIX path as Finder window title
  shell: "defaults write com.apple.finder _FXShowPosixPathInTitle -bool true"

- name: Avoid creating .DS_Store files on network volumes
  shell: "defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true"

- name: # Use list view in all Finder windows by default.
  shell: "defaults write com.apple.finder FXPreferredViewStyle -string \"Nlsv\""

- name: Set dock tile size
  shell: "defaults write com.apple.dock tilesize -int 30"

- name: Set dock tile large size
  shell: "defaults write com.apple.dock largesize -int 60"

- name: Autohide dock
  shell: "defaults write com.apple.dock autohide -bool true"

- name: Disable the crash reporter
  shell: "defaults write com.apple.CrashReporter DialogType -string \"none\""

- name: Don’t display the annoying prompt when quitting iTerm
  shell: "defaults write com.googlecode.iterm2 PromptOnQuit -bool false"

- name: Disable useless dashboard
  shell: "defaults write com.apple.dashboard mcx-disabled -boolean YES && killall Dock"
